# Generated by Django 5.0.14 on 2026-05-07 18:01

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("appointments", "0001_initial"),
        ("clinics", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Patient",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                (
                    "second_last_name",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, db_index=True, default="", max_length=254
                    ),
                ),
                ("phone", models.CharField(db_index=True, max_length=15)),
                (
                    "alternate_phone",
                    models.CharField(blank=True, default="", max_length=15),
                ),
                (
                    "curp",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=18
                    ),
                ),
                ("rfc", models.CharField(blank=True, default="", max_length=13)),
                ("date_of_birth", models.DateField()),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("M", "Masculino"),
                            ("F", "Femenino"),
                            ("O", "Otro"),
                            ("N", "Prefiere no decir"),
                        ],
                        default="N",
                        max_length=1,
                    ),
                ),
                ("address", models.JSONField(blank=True, default=dict)),
                (
                    "occupation",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                (
                    "emergency_contact_name",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                (
                    "emergency_contact_phone",
                    models.CharField(blank=True, default="", max_length=15),
                ),
                (
                    "emergency_contact_relation",
                    models.CharField(blank=True, default="", max_length=50),
                ),
                (
                    "blood_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("A+", "A+"),
                            ("A-", "A-"),
                            ("B+", "B+"),
                            ("B-", "B-"),
                            ("AB+", "AB+"),
                            ("AB-", "AB-"),
                            ("O+", "O+"),
                            ("O-", "O-"),
                        ],
                        default="",
                        max_length=3,
                    ),
                ),
                (
                    "allergies",
                    models.TextField(
                        blank=True, default="", help_text="Encrypted: patient allergies"
                    ),
                ),
                (
                    "chronic_conditions",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Encrypted: chronic medical conditions",
                    ),
                ),
                (
                    "current_medications",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Encrypted: current medications",
                    ),
                ),
                (
                    "insurance_provider",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                (
                    "insurance_policy_number",
                    models.CharField(blank=True, default="", max_length=50),
                ),
                ("whatsapp_opt_in", models.BooleanField(default=True)),
                ("email_opt_in", models.BooleanField(default=True)),
                ("consent_signed", models.BooleanField(default=False)),
                ("consent_signed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "consent_version",
                    models.CharField(blank=True, default="", max_length=20),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "clinic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="patients",
                        to="clinics.clinic",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_patients",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "patients",
                "ordering": ["last_name", "first_name"],
            },
        ),
        migrations.CreateModel(
            name="ClinicalNote",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "note_type",
                    models.CharField(
                        choices=[
                            ("evolution", "Evolución"),
                            ("diagnosis", "Diagnóstico"),
                            ("treatment", "Tratamiento"),
                            ("observation", "Observación"),
                            ("consent", "Consentimiento"),
                        ],
                        default="evolution",
                        max_length=30,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                (
                    "content",
                    models.TextField(help_text="Encrypted: clinical note content"),
                ),
                ("is_signed", models.BooleanField(default=False)),
                ("signed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "signature_hash",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                ("attachments", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "appointment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="clinical_notes",
                        to="appointments.appointment",
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="clinical_notes",
                        to="patients.patient",
                    ),
                ),
            ],
            options={
                "db_table": "clinical_notes",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PatientConsent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "consent_type",
                    models.CharField(
                        choices=[
                            ("general", "Consentimiento General"),
                            ("treatment", "Consentimiento de Tratamiento"),
                            ("data_processing", "Consentimiento de Datos"),
                            ("whatsapp", "Consentimiento WhatsApp"),
                        ],
                        max_length=50,
                    ),
                ),
                ("version", models.CharField(default="1.0", max_length=20)),
                (
                    "content",
                    models.TextField(
                        help_text="Consent template content at time of signing"
                    ),
                ),
                ("signed", models.BooleanField(default=False)),
                ("signed_at", models.DateTimeField(blank=True, null=True)),
                ("signature_blob", models.BinaryField(blank=True, null=True)),
                (
                    "signature_hash",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="consents",
                        to="patients.patient",
                    ),
                ),
                (
                    "signed_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "patient_consents",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="patient",
            index=models.Index(
                fields=["clinic", "last_name", "first_name"], name="idx_patients_name"
            ),
        ),
        migrations.AddIndex(
            model_name="patient",
            index=models.Index(fields=["clinic", "phone"], name="idx_patients_phone"),
        ),
        migrations.AddIndex(
            model_name="patient",
            index=models.Index(fields=["clinic", "email"], name="idx_patients_email"),
        ),
        migrations.AddIndex(
            model_name="patient",
            index=models.Index(fields=["curp"], name="idx_patients_curp"),
        ),
        migrations.AddIndex(
            model_name="patient",
            index=models.Index(
                fields=["clinic", "created_at"], name="idx_patients_created"
            ),
        ),
        migrations.AddConstraint(
            model_name="patient",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_deleted", False)),
                fields=("clinic", "phone"),
                name="uq_patient_clinic_phone",
            ),
        ),
        migrations.AddIndex(
            model_name="clinicalnote",
            index=models.Index(
                fields=["patient", "created_at"], name="idx_notes_patient_date"
            ),
        ),
        migrations.AddIndex(
            model_name="clinicalnote",
            index=models.Index(
                fields=["patient", "note_type"], name="idx_notes_patient_type"
            ),
        ),
        migrations.AddIndex(
            model_name="clinicalnote",
            index=models.Index(fields=["appointment"], name="idx_notes_appointment"),
        ),
        migrations.AddIndex(
            model_name="patientconsent",
            index=models.Index(
                fields=["patient", "consent_type"], name="idx_consents_patient_type"
            ),
        ),
    ]
