# Generated by Django 5.0.14 (SDD apply — odontograma-historia-clinica PR#1)

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("patients", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="clinicalnote",
            name="tooth_fdi",
            field=models.IntegerField(
                blank=True,
                null=True,
                help_text="FDI tooth number (11-48 permanent, 51-85 primary)",
            ),
        ),
        migrations.AddField(
            model_name="clinicalnote",
            name="surface",
            field=models.CharField(
                blank=True,
                null=True,
                max_length=20,
                choices=[
                    ("mesial", "Mesial"),
                    ("distal", "Distal"),
                    ("buccal", "Bucal"),
                    ("lingual", "Lingual"),
                    ("occlusal", "Oclusal"),
                    ("root", "Raíz"),
                ],
                help_text="Tooth surface referenced in this note",
            ),
        ),
    ]
