# Generated by Django 5.0.14 on 2026-05-07 18:01

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("appointments", "0002_initial"),
        ("clinics", "0001_initial"),
        ("patients", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="WhatsAppWebhook",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("from_number", models.CharField(max_length=50)),
                ("to_number", models.CharField(max_length=50)),
                ("message_body", models.TextField(blank=True, default="")),
                (
                    "direction",
                    models.CharField(
                        choices=[
                            ("inbound", "Entrante"),
                            ("outbound", "Saliente"),
                            ("status", "Status callback"),
                        ],
                        default="inbound",
                        max_length=20,
                    ),
                ),
                (
                    "twilio_sid",
                    models.CharField(
                        help_text="Unique Twilio message/event SID",
                        max_length=200,
                        unique=True,
                    ),
                ),
                (
                    "processed",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this webhook has been processed",
                    ),
                ),
                (
                    "action_taken",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Description of action taken (e.g., 'appointment_confirmed')",
                        max_length=200,
                    ),
                ),
                ("received_at", models.DateTimeField(auto_now_add=True)),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "clinic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="whatsapp_webhooks",
                        to="clinics.clinic",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="whatsapp_webhooks",
                        to="patients.patient",
                    ),
                ),
            ],
            options={
                "db_table": "whatsapp_webhooks",
                "ordering": ["-received_at"],
            },
        ),
        migrations.CreateModel(
            name="NotificationLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "channel",
                    models.CharField(
                        choices=[
                            ("whatsapp", "WhatsApp"),
                            ("sms", "SMS"),
                            ("email", "Email"),
                        ],
                        default="whatsapp",
                        max_length=20,
                    ),
                ),
                (
                    "template",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Template name used (e.g., appointment_reminder)",
                        max_length=100,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "En cola"),
                            ("sent", "Enviado"),
                            ("delivered", "Entregado"),
                            ("read", "Leído"),
                            ("failed", "Fallido"),
                            ("undelivered", "No entregado"),
                        ],
                        db_index=True,
                        default="queued",
                        max_length=20,
                    ),
                ),
                (
                    "recipient",
                    models.CharField(
                        help_text="Phone number or email of the recipient",
                        max_length=50,
                    ),
                ),
                ("content", models.TextField(help_text="Rendered message content")),
                (
                    "provider_id",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Twilio message SID or equivalent",
                        max_length=200,
                    ),
                ),
                (
                    "provider_response",
                    models.JSONField(
                        blank=True, default=dict, help_text="Full provider API response"
                    ),
                ),
                ("error_message", models.TextField(blank=True, default="")),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("delivered_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "appointment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="notification_logs",
                        to="appointments.appointment",
                    ),
                ),
                (
                    "clinic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification_logs",
                        to="clinics.clinic",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="notification_logs",
                        to="patients.patient",
                    ),
                ),
            ],
            options={
                "db_table": "notification_logs",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["clinic", "status"], name="idx_notif_logs_clinic_status"
                    ),
                    models.Index(
                        fields=["clinic", "channel"],
                        name="idx_notif_logs_clinic_channel",
                    ),
                    models.Index(
                        fields=["patient", "created_at"],
                        name="idx_notif_logs_patient_date",
                    ),
                    models.Index(
                        fields=["appointment", "created_at"],
                        name="idx_notif_logs_appt_date",
                    ),
                    models.Index(
                        fields=["provider_id"], name="idx_notif_logs_provider_id"
                    ),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="notificationlog",
            constraint=models.CheckConstraint(
                check=models.Q(("recipient", ""), _negated=True),
                name="chk_notif_log_recipient_not_empty",
            ),
        ),
        migrations.AddConstraint(
            model_name="notificationlog",
            constraint=models.CheckConstraint(
                check=models.Q(("content", ""), _negated=True),
                name="chk_notif_log_content_not_empty",
            ),
        ),
        migrations.AddIndex(
            model_name="whatsappwebhook",
            index=models.Index(
                fields=["clinic", "processed"], name="idx_webhooks_clinic_processed"
            ),
        ),
        migrations.AddIndex(
            model_name="whatsappwebhook",
            index=models.Index(
                fields=["from_number", "received_at"], name="idx_webhooks_from_date"
            ),
        ),
        migrations.AddConstraint(
            model_name="whatsappwebhook",
            constraint=models.UniqueConstraint(
                fields=("twilio_sid",), name="idx_webhooks_twilio_sid"
            ),
        ),
    ]
