"""
CFDI Invoicing models.

Models:
- FiscalConfig: Clinic fiscal data for CFDI issuance (RFC, CSD certificates, etc.)
- Invoice: CFDI invoice records with SAT stamping status

All models enforce tenant isolation via clinic FK + RLS.
"""

import uuid
from typing import Any

from django.db import models
from django.utils import timezone


# ---------------------------------------------------------------------------
# FiscalConfig Model
# ---------------------------------------------------------------------------


class FiscalConfig(models.Model):
    """
    Clinic fiscal configuration for CFDI 4.0 issuance.

    Stores the clinic's RFC, razón social, régimen fiscal, and CSD (Certificado
    de Sello Digital) certificate/key pair required by the SAT for stamping.

    Only ONE fiscal config per clinic — the PK is the clinic FK.
    """

    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    clinic = models.OneToOneField(
        "clinics.Clinic",
        on_delete=models.CASCADE,
        related_name="fiscal_config",
    )

    # Fiscal identity
    rfc = models.CharField(
        max_length=13,
        db_index=True,
        help_text="RFC de la clínica (12-13 caracteres)",
    )
    razon_social = models.CharField(
        max_length=255,
        help_text="Razón social tal como aparece en la Constancia de Situación Fiscal",
    )
    regimen_fiscal = models.CharField(
        max_length=3,
        help_text="Clave del régimen fiscal SAT (e.g., 601, 606, 612)",
    )
    fiscal_address = models.JSONField(
        default=dict,
        blank=True,
        help_text="Dirección fiscal: {calle, no_exterior, no_interior, colonia, localidad, municipio, estado, pais, codigo_postal}",
    )

    # CSD (Certificado de Sello Digital)
    csd_cert_path = models.CharField(
        max_length=500,
        blank=True,
        default="",
        help_text="Path al archivo .cer del CSD",
    )
    csd_key_path = models.CharField(
        max_length=500,
        blank=True,
        default="",
        help_text="Path al archivo .key del CSD",
    )
    csd_password_encrypted = models.BinaryField(
        blank=True,
        null=True,
        help_text="Contraseña del CSD encriptada con AES-256-GCM",
    )

    # Contact for CFDI delivery
    email = models.EmailField(
        blank=True,
        default="",
        help_text="Email para envío de facturas",
    )

    # Validation
    is_validated = models.BooleanField(
        default=False,
        help_text="True si el CSD fue validado exitosamente contra el SAT",
    )

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        db_table = "fiscal_configs"
        ordering = ["-created_at"]
        indexes = [
            models.Index(fields=["rfc"], name="idx_fiscal_rfc"),
        ]

    def __str__(self) -> str:
        return f"{self.razon_social} ({self.rfc})"


# ---------------------------------------------------------------------------
# Invoice Model
# ---------------------------------------------------------------------------


class Invoice(models.Model):
    """
    CFDI 4.0 invoice record.

    Status flow:
    draft → pending_stamp → stamped → sent → paid
    Alternative: draft → cancelled, stamped → cancellation_requested → cancelled

    The actual CFDI XML is generated by the CFDI builder service and sent to
    Finkok (PAC) for stamping. The SAT returns a UUID and signed XML.
    """

    class Status(models.TextChoices):
        DRAFT = "draft", "Borrador"
        PENDING_STAMP = "pending_stamp", "Pendiente de timbrado"
        STAMPED = "stamped", "Timbrada"
        SENT = "sent", "Enviada al cliente"
        PAID = "paid", "Pagada"
        CANCELLED = "cancelled", "Cancelada"
        CANCELLATION_REQUESTED = "cancellation_requested", "Cancelación solicitada"
        ERROR = "error", "Error"

    class MetodoPago(models.TextChoices):
        PUE = "PUE", "Pago en una sola exhibición"
        PPD = "PPD", "Pago en parcialidades o diferido"

    class FormaPago(models.TextChoices):
        EFECTIVO = "01", "Efectivo"
        TARJETA = "04", "Tarjeta de débito"
        TRANSFERENCIA = "03", "Transferencia electrónica"
        CREDITO = "06", "Monedero electrónico"
        OTRO = "99", "Por definir"

    class UsoCFDI(models.TextChoices):
        G03 = "G03", "Gastos en general"
        D01 = "D01", "Honorarios médicos, dentales y gastos hospitalarios"
        S01 = "S01", "Sin efectos fiscales"
        CP01 = "CP01", "Pagos"

    class Moneda(models.TextChoices):
        MXN = "MXN", "Peso Mexicano"
        USD = "USD", "Dólar Estadounidense"

    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    clinic = models.ForeignKey(
        "clinics.Clinic",
        on_delete=models.CASCADE,
        related_name="invoices",
    )
    patient = models.ForeignKey(
        "patients.Patient",
        on_delete=models.PROTECT,
        related_name="invoices",
    )
    appointment = models.ForeignKey(
        "appointments.Appointment",
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name="invoices",
    )

    # Invoice numbering (per-clinic sequential)
    folio = models.CharField(
        max_length=20,
        db_index=True,
        help_text="Folio consecutivo de la factura",
    )

    # Receptor (patient) fiscal data
    rfc_receptor = models.CharField(
        max_length=13,
        db_index=True,
        help_text="RFC del paciente/receptor",
    )
    nombre_receptor = models.CharField(
        max_length=255,
        help_text="Nombre o razón social del receptor",
    )
    uso_cfdi = models.CharField(
        max_length=10,
        choices=UsoCFDI.choices,
        default=UsoCFDI.G03,
        help_text="Uso de CFDI según catálogo SAT",
    )

    # Payment terms
    metodo_pago = models.CharField(
        max_length=3,
        choices=MetodoPago.choices,
        default=MetodoPago.PUE,
    )
    forma_pago = models.CharField(
        max_length=2,
        choices=FormaPago.choices,
        default=FormaPago.EFECTIVO,
    )
    moneda = models.CharField(
        max_length=3,
        choices=Moneda.choices,
        default=Moneda.MXN,
    )

    # Amounts
    subtotal = models.DecimalField(
        max_digits=12,
        decimal_places=2,
        default=0,
        help_text="Suma de los importes antes de impuestos",
    )
    iva = models.DecimalField(
        max_digits=12,
        decimal_places=2,
        default=0,
        help_text="IVA (16% typically)",
    )
    total = models.DecimalField(
        max_digits=12,
        decimal_places=2,
        default=0,
        help_text="subtotal + iva",
    )

    # Line items
    concepts = models.JSONField(
        default=list,
        help_text="Lista de conceptos: [{clave_sat, descripcion, cantidad, unidad, valor_unitario, importe, iva_rate}]",
    )

    # Status tracking
    status = models.CharField(
        max_length=30,
        choices=Status.choices,
        default=Status.DRAFT,
        db_index=True,
    )

    # CFDI stamping data (populated after Finkok stamps)
    cfdi_uuid = models.CharField(
        max_length=36,
        blank=True,
        default="",
        db_index=True,
        help_text="UUID del CFDI asignado por el SAT",
    )
    xml_url = models.CharField(
        max_length=500,
        blank=True,
        default="",
        help_text="URL para descargar el XML timbrado",
    )
    pdf_url = models.CharField(
        max_length=500,
        blank=True,
        default="",
        help_text="URL para descargar la representación impresa PDF",
    )
    cfdi_sat_certificate = models.CharField(
        max_length=40,
        blank=True,
        default="",
        help_text="Número de certificado del SAT usado para timbrar",
    )
    cfdi_stamp_date = models.DateTimeField(
        blank=True,
        null=True,
        help_text="Fecha de timbrado del CFDI",
    )

    # Cancellation fields
    cancellation_reason = models.CharField(
        max_length=20,
        blank=True,
        default="",
        help_text="Motivo de cancelación SAT: 01, 02, 03, 04",
    )
    cancellation_folio = models.CharField(
        max_length=200,
        blank=True,
        default="",
        help_text="Folio de sustitución si aplica (motivo 01)",
    )
    cancelled_at = models.DateTimeField(blank=True, null=True)

    # Error tracking
    error_message = models.TextField(
        blank=True,
        default="",
        help_text="Mensaje de error del último intento de timbrado",
    )

    # Audit
    created_by = models.ForeignKey(
        "accounts.User",
        on_delete=models.SET_NULL,
        null=True,
        related_name="created_invoices",
    )

    # Timestamps
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        db_table = "invoices"
        ordering = ["-created_at"]
        indexes = [
            models.Index(
                fields=["clinic", "status"], name="idx_invoices_clinic_status"
            ),
            models.Index(fields=["clinic", "created_at"], name="idx_invoices_created"),
            models.Index(fields=["patient", "created_at"], name="idx_invoices_patient"),
            models.Index(fields=["cfdi_uuid"], name="idx_invoices_uuid"),
            models.Index(fields=["folio"], name="idx_invoices_folio"),
        ]
        constraints = [
            models.UniqueConstraint(
                fields=["clinic", "folio"],
                name="uq_invoice_clinic_folio",
            ),
        ]

    def __str__(self) -> str:
        return f"Factura {self.folio} — {self.nombre_receptor} ({self.get_status_display()})"

    @property
    def patient_name(self) -> str:
        """Return the patient's full name."""
        return self.patient.full_name

    def cancel(
        self, reason: str = "01", folio_sustitucion: str = "", user=None
    ) -> None:
        """
        Request cancellation of this CFDI.

        SAT cancellation reasons:
        01 — Comprobante emitido con errores con relación
        02 — Comprobante emitido con errores sin relación
        03 — No se llevó a cabo la operación
        04 — Operación nominativa relacionada en una global
        """
        if self.status not in (self.Status.STAMPED, self.Status.SENT, self.Status.PAID):
            raise ValueError(
                "Solo se pueden cancelar facturas timbradas, enviadas o pagadas."
            )

        self.status = self.Status.CANCELLATION_REQUESTED
        self.cancellation_reason = reason
        self.cancellation_folio = folio_sustitucion
        self.save(
            update_fields=[
                "status",
                "cancellation_reason",
                "cancellation_folio",
                "updated_at",
            ]
        )

    def mark_cancelled(self) -> None:
        """Mark invoice as cancelled after SAT confirms cancellation."""
        if self.status != self.Status.CANCELLATION_REQUESTED:
            raise ValueError("La factura debe estar en estado cancellation_requested.")

        self.status = self.Status.CANCELLED
        self.cancelled_at = timezone.now()
        self.save(update_fields=["status", "cancelled_at", "updated_at"])

    def mark_stamped(
        self,
        uuid: str,
        sat_certificate: str,
        stamp_date: Any,
        xml_url: str = "",
        pdf_url: str = "",
    ) -> None:
        """Mark invoice as successfully stamped by SAT via Finkok."""
        self.status = self.Status.STAMPED
        self.cfdi_uuid = uuid
        self.cfdi_sat_certificate = sat_certificate
        self.cfdi_stamp_date = stamp_date
        self.xml_url = xml_url
        self.pdf_url = pdf_url
        self.error_message = ""
        self.save(
            update_fields=[
                "status",
                "cfdi_uuid",
                "cfdi_sat_certificate",
                "cfdi_stamp_date",
                "xml_url",
                "pdf_url",
                "error_message",
                "updated_at",
            ]
        )

    def mark_error(self, message: str) -> None:
        """Record a stamping error."""
        self.status = self.Status.ERROR
        self.error_message = message
        self.save(update_fields=["status", "error_message", "updated_at"])

    def calculate_totals(self) -> None:
        """Recalculate subtotal, iva, and total from concepts."""
        subtotal = sum(concept.get("importe", 0) for concept in self.concepts)
        iva = sum(
            concept.get("importe", 0) * concept.get("iva_rate", 0.16)
            for concept in self.concepts
        )
        self.subtotal = round(subtotal, 2)
        self.iva = round(iva, 2)
        self.total = round(self.subtotal + self.iva, 2)
