# Generated by Django 5.0.14 (auto-generated via SDD apply)

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import dental_records.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("patients", "0001_initial"),
        ("appointments", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # ── 1. DentalRecordEntry ────────────────────────────────────────
        migrations.CreateModel(
            name="DentalRecordEntry",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("tooth_fdi", models.IntegerField()),
                (
                    "surface",
                    models.CharField(
                        choices=[
                            ("mesial", "Mesial"),
                            ("distal", "Distal"),
                            ("buccal", "Bucal"),
                            ("lingual", "Lingual"),
                            ("occlusal", "Oclusal"),
                            ("root", "Raíz"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "condition",
                    models.CharField(
                        choices=[
                            ("healthy", "Sano"),
                            ("caries", "Caries"),
                            ("filling", "Obturado"),
                            ("crown", "Corona"),
                            ("bridge", "Puente"),
                            ("missing", "Ausente"),
                            ("implant", "Implante"),
                            ("root_canal", "Endodoncia"),
                            ("extraction", "Extracción"),
                            ("fracture", "Fractura"),
                            ("wear", "Desgaste"),
                            ("sealant", "Sellador"),
                            ("prosthesis", "Prótesis"),
                            ("other", "Otro"),
                        ],
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dental_records",
                        to="patients.patient",
                    ),
                ),
            ],
            options={
                "db_table": "dental_records_entries",
                "ordering": ["-created_at"],
            },
        ),
        # ── 2. Tooth (materialized) ─────────────────────────────────────
        migrations.CreateModel(
            name="Tooth",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("tooth_fdi", models.IntegerField()),
                (
                    "condition",
                    models.CharField(
                        choices=[
                            ("healthy", "Sano"),
                            ("caries", "Caries"),
                            ("filling", "Obturado"),
                            ("crown", "Corona"),
                            ("bridge", "Puente"),
                            ("missing", "Ausente"),
                            ("implant", "Implante"),
                            ("root_canal", "Endodoncia"),
                            ("extraction", "Extracción"),
                            ("fracture", "Fractura"),
                            ("wear", "Desgaste"),
                            ("sealant", "Sellador"),
                            ("prosthesis", "Prótesis"),
                            ("other", "Otro"),
                        ],
                        max_length=20,
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "last_entry",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="dental_records.dentalrecordentry",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="teeth",
                        to="patients.patient",
                    ),
                ),
            ],
            options={
                "db_table": "dental_records_teeth",
            },
        ),
        # ── 3. ToothSurface (materialized) ──────────────────────────────
        migrations.CreateModel(
            name="ToothSurface",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "surface",
                    models.CharField(
                        choices=[
                            ("mesial", "Mesial"),
                            ("distal", "Distal"),
                            ("buccal", "Bucal"),
                            ("lingual", "Lingual"),
                            ("occlusal", "Oclusal"),
                            ("root", "Raíz"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "condition",
                    models.CharField(
                        choices=[
                            ("healthy", "Sano"),
                            ("caries", "Caries"),
                            ("filling", "Obturado"),
                            ("crown", "Corona"),
                            ("bridge", "Puente"),
                            ("missing", "Ausente"),
                            ("implant", "Implante"),
                            ("root_canal", "Endodoncia"),
                            ("extraction", "Extracción"),
                            ("fracture", "Fractura"),
                            ("wear", "Desgaste"),
                            ("sealant", "Sellador"),
                            ("prosthesis", "Prótesis"),
                            ("other", "Otro"),
                        ],
                        max_length=20,
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "last_entry",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="dental_records.dentalrecordentry",
                    ),
                ),
                (
                    "tooth",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="surfaces",
                        to="dental_records.tooth",
                    ),
                ),
            ],
            options={
                "db_table": "dental_records_tooth_surfaces",
            },
        ),
        # ── 4. MedicalHistory ───────────────────────────────────────────
        migrations.CreateModel(
            name="MedicalHistory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("version", models.IntegerField(default=1)),
                (
                    "antecedentes_patologicos",
                    models.JSONField(blank=True, default=list),
                ),
                (
                    "antecedentes_quirurgicos",
                    models.JSONField(blank=True, default=list),
                ),
                (
                    "antecedentes_alergicos",
                    models.JSONField(blank=True, default=list),
                ),
                (
                    "antecedentes_farmacologicos",
                    models.JSONField(blank=True, default=list),
                ),
                (
                    "antecedentes_familiares",
                    models.JSONField(blank=True, default=list),
                ),
                (
                    "motivo_consulta",
                    models.TextField(blank=True, default=""),
                ),
                (
                    "enfermedad_actual",
                    models.TextField(blank=True, default=""),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_medical_histories",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="medical_histories",
                        to="patients.patient",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_medical_histories",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "dental_records_medical_histories",
                "ordering": ["-version"],
            },
        ),
        # ── 5. VitalSigns ───────────────────────────────────────────────
        migrations.CreateModel(
            name="VitalSigns",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "blood_pressure_systolic",
                    models.IntegerField(blank=True, null=True),
                ),
                (
                    "blood_pressure_diastolic",
                    models.IntegerField(blank=True, null=True),
                ),
                ("heart_rate", models.IntegerField(blank=True, null=True)),
                (
                    "temperature",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=4, null=True
                    ),
                ),
                (
                    "weight",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "height",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("notes", models.TextField(blank=True, default="")),
                ("recorded_at", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "appointment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="vital_signs",
                        to="appointments.appointment",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vital_signs",
                        to="patients.patient",
                    ),
                ),
                (
                    "recorded_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "dental_records_vital_signs",
                "ordering": ["-recorded_at"],
            },
        ),
        # ── 6. PatientImage ─────────────────────────────────────────────
        migrations.CreateModel(
            name="PatientImage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "tooth_fdi",
                    models.IntegerField(blank=True, null=True),
                ),
                (
                    "image_type",
                    models.CharField(
                        choices=[
                            ("photo", "Foto Clínica"),
                            ("xray_periapical", "Radiografía Periapical"),
                            ("xray_panoramic", "Radiografía Panorámica"),
                            ("xray_cephalometric", "Radiografía Cefalométrica"),
                            ("document", "Documento"),
                            ("other", "Otro"),
                        ],
                        default="photo",
                        max_length=30,
                    ),
                ),
                (
                    "image",
                    models.ImageField(upload_to=dental_records.models.get_image_path),
                ),
                (
                    "thumbnail",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=dental_records.models.get_image_path,
                    ),
                ),
                ("description", models.TextField(blank=True, default="")),
                ("file_size", models.IntegerField(blank=True, null=True)),
                (
                    "content_type",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="patients.patient",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "dental_records_patient_images",
                "ordering": ["-uploaded_at"],
            },
        ),
        # ── 7. TreatmentPlan ────────────────────────────────────────────
        migrations.CreateModel(
            name="TreatmentPlan",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True, default="")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Activo"),
                            ("completed", "Completado"),
                            ("cancelled", "Cancelado"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="treatment_plans",
                        to="patients.patient",
                    ),
                ),
            ],
            options={
                "db_table": "dental_records_treatment_plans",
                "ordering": ["-created_at"],
            },
        ),
        # ── 8. TreatmentPhase ───────────────────────────────────────────
        migrations.CreateModel(
            name="TreatmentPhase",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True, default="")),
                ("order", models.IntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pendiente"),
                            ("in_progress", "En curso"),
                            ("completed", "Completado"),
                            ("cancelled", "Cancelado"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="phases",
                        to="dental_records.treatmentplan",
                    ),
                ),
            ],
            options={
                "db_table": "dental_records_treatment_phases",
                "ordering": ["order"],
            },
        ),
        # ── 9. TreatmentProcedure ───────────────────────────────────────
        migrations.CreateModel(
            name="TreatmentProcedure",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "tooth_fdi",
                    models.IntegerField(blank=True, null=True),
                ),
                ("description", models.TextField()),
                (
                    "cost",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("planned", "Planeado"),
                            ("in_progress", "En curso"),
                            ("completed", "Realizado"),
                            ("cancelled", "Cancelado"),
                        ],
                        default="planned",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True, default="")),
                (
                    "appointment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="treatment_procedures",
                        to="appointments.appointment",
                    ),
                ),
                (
                    "phase",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="procedures",
                        to="dental_records.treatmentphase",
                    ),
                ),
            ],
            options={
                "db_table": "dental_records_treatment_procedures",
                "ordering": ["phase__order", "id"],
            },
        ),
        # ── Indexes and Constraints (added via separate RunSQL after model creation)
        migrations.RunSQL(
            sql="""
                CREATE INDEX IF NOT EXISTS idx_dre_patient_tooth ON dental_records_entries (patient_id, tooth_fdi);
                CREATE INDEX IF NOT EXISTS idx_dre_patient_date ON dental_records_entries (patient_id, created_at);
                CREATE UNIQUE INDEX IF NOT EXISTS uq_tooth_patient_fdi ON dental_records_teeth (patient_id, tooth_fdi);
                CREATE INDEX IF NOT EXISTS idx_tooth_patient_cond ON dental_records_teeth (patient_id, condition);
                CREATE UNIQUE INDEX IF NOT EXISTS uq_tooth_surface ON dental_records_tooth_surfaces (tooth_id, surface);
                CREATE UNIQUE INDEX IF NOT EXISTS uq_medical_history_patient_version ON dental_records_medical_histories (patient_id, version);
                CREATE INDEX IF NOT EXISTS idx_mh_patient_active ON dental_records_medical_histories (patient_id, is_active);
                CREATE INDEX IF NOT EXISTS idx_vs_patient_date ON dental_records_vital_signs (patient_id, recorded_at);
                CREATE INDEX IF NOT EXISTS idx_pi_patient_type ON dental_records_patient_images (patient_id, image_type);
                CREATE INDEX IF NOT EXISTS idx_pi_patient_tooth ON dental_records_patient_images (patient_id, tooth_fdi);
            """,
            reverse_sql="""
                DROP INDEX IF EXISTS idx_dre_patient_tooth;
                DROP INDEX IF EXISTS idx_dre_patient_date;
                DROP INDEX IF EXISTS uq_tooth_patient_fdi;
                DROP INDEX IF EXISTS idx_tooth_patient_cond;
                DROP INDEX IF EXISTS uq_tooth_surface;
                DROP INDEX IF EXISTS uq_medical_history_patient_version;
                DROP INDEX IF EXISTS idx_mh_patient_active;
                DROP INDEX IF EXISTS idx_vs_patient_date;
                DROP INDEX IF EXISTS idx_pi_patient_type;
                DROP INDEX IF EXISTS idx_pi_patient_tooth;
            """,
        ),
    ]
