# Generated by Django 5.0.14 on 2026-06-01 16:44

import dental_records.models
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_appointment_inventory_consumed_at'),
        ('dental_records', '0001_initial'),
        ('patients', '0002_add_clinical_note_dental_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='dentalrecordentry',
            name='tooth_fdi',
            field=models.IntegerField(validators=[dental_records.models.validate_fdi]),
        ),
        migrations.AlterField(
            model_name='medicalhistory',
            name='antecedentes_alergicos',
            field=models.JSONField(blank=True, default=list, help_text='Lista de { "alergeno": str, "reaccion": str, "notas": str }'),
        ),
        migrations.AlterField(
            model_name='medicalhistory',
            name='antecedentes_familiares',
            field=models.JSONField(blank=True, default=list, help_text='Lista de { "parentesco": str, "enfermedad": str, "notas": str }'),
        ),
        migrations.AlterField(
            model_name='medicalhistory',
            name='antecedentes_farmacologicos',
            field=models.JSONField(blank=True, default=list, help_text='Lista de { "medicamento": str, "dosis": str, "notas": str }'),
        ),
        migrations.AlterField(
            model_name='medicalhistory',
            name='antecedentes_patologicos',
            field=models.JSONField(blank=True, default=list, help_text='Lista de { "enfermedad": str, "notas": str }'),
        ),
        migrations.AlterField(
            model_name='medicalhistory',
            name='antecedentes_quirurgicos',
            field=models.JSONField(blank=True, default=list, help_text='Lista de { "procedimiento": str, "fecha": str, "notas": str }'),
        ),
        migrations.AlterField(
            model_name='medicalhistory',
            name='enfermedad_actual',
            field=models.TextField(blank=True, default='', verbose_name='Enfermedad actual'),
        ),
        migrations.AlterField(
            model_name='medicalhistory',
            name='motivo_consulta',
            field=models.TextField(blank=True, default='', verbose_name='Motivo de consulta'),
        ),
        migrations.AlterField(
            model_name='patientimage',
            name='content_type',
            field=models.CharField(blank=True, default='', help_text='MIME type of the uploaded file', max_length=100),
        ),
        migrations.AlterField(
            model_name='patientimage',
            name='file_size',
            field=models.IntegerField(blank=True, help_text='File size in bytes', null=True),
        ),
        migrations.AlterField(
            model_name='patientimage',
            name='tooth_fdi',
            field=models.IntegerField(blank=True, help_text='Optional link to a specific tooth', null=True, validators=[dental_records.models.validate_fdi]),
        ),
        migrations.AlterField(
            model_name='tooth',
            name='tooth_fdi',
            field=models.IntegerField(validators=[dental_records.models.validate_fdi]),
        ),
        migrations.AlterField(
            model_name='treatmentprocedure',
            name='tooth_fdi',
            field=models.IntegerField(blank=True, null=True, validators=[dental_records.models.validate_fdi]),
        ),
        migrations.AlterField(
            model_name='vitalsigns',
            name='recorded_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddIndex(
            model_name='dentalrecordentry',
            index=models.Index(fields=['patient', 'tooth_fdi'], name='idx_dre_patient_tooth'),
        ),
        migrations.AddIndex(
            model_name='dentalrecordentry',
            index=models.Index(fields=['patient', 'created_at'], name='idx_dre_patient_date'),
        ),
        migrations.AddIndex(
            model_name='medicalhistory',
            index=models.Index(fields=['patient', 'is_active'], name='idx_mh_patient_active'),
        ),
        migrations.AddIndex(
            model_name='patientimage',
            index=models.Index(fields=['patient', 'image_type'], name='idx_pi_patient_type'),
        ),
        migrations.AddIndex(
            model_name='patientimage',
            index=models.Index(fields=['patient', 'tooth_fdi'], name='idx_pi_patient_tooth'),
        ),
        migrations.AddIndex(
            model_name='tooth',
            index=models.Index(fields=['patient', 'condition'], name='idx_tooth_patient_cond'),
        ),
        migrations.AddIndex(
            model_name='vitalsigns',
            index=models.Index(fields=['patient', 'recorded_at'], name='idx_vs_patient_date'),
        ),
        migrations.AddConstraint(
            model_name='medicalhistory',
            constraint=models.UniqueConstraint(fields=('patient', 'version'), name='uq_medical_history_patient_version'),
        ),
        migrations.AddConstraint(
            model_name='tooth',
            constraint=models.UniqueConstraint(fields=('patient', 'tooth_fdi'), name='uq_tooth_patient_fdi'),
        ),
        migrations.AddConstraint(
            model_name='toothsurface',
            constraint=models.UniqueConstraint(fields=('tooth', 'surface'), name='uq_tooth_surface'),
        ),
    ]
