# Generated by Django 5.0.14 on 2026-05-07 18:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("appointments", "0001_initial"),
        ("clinics", "0001_initial"),
        ("patients", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="patient",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="appointments",
                to="patients.patient",
            ),
        ),
        migrations.AddField(
            model_name="appointmenttype",
            name="clinic",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="appointment_types",
                to="clinics.clinic",
            ),
        ),
        migrations.AddField(
            model_name="appointment",
            name="appointment_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="appointments",
                to="appointments.appointmenttype",
            ),
        ),
        migrations.AddField(
            model_name="scheduleslot",
            name="clinic",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="schedule_slots",
                to="clinics.clinic",
            ),
        ),
        migrations.AddField(
            model_name="scheduleslot",
            name="dentist",
            field=models.ForeignKey(
                blank=True,
                help_text="Null = applies to all dentists (clinic-wide schedule)",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="schedule_slots",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="appointmenttype",
            index=models.Index(
                fields=["clinic", "is_active"], name="idx_appt_types_active"
            ),
        ),
        migrations.AddIndex(
            model_name="appointment",
            index=models.Index(fields=["clinic", "date"], name="idx_appts_clinic_date"),
        ),
        migrations.AddIndex(
            model_name="appointment",
            index=models.Index(fields=["clinic", "status"], name="idx_appts_status"),
        ),
        migrations.AddIndex(
            model_name="appointment",
            index=models.Index(
                fields=["patient", "date"], name="idx_appts_patient_date"
            ),
        ),
        migrations.AddIndex(
            model_name="appointment",
            index=models.Index(
                fields=["dentist", "date"], name="idx_appts_dentist_date"
            ),
        ),
        migrations.AddIndex(
            model_name="appointment",
            index=models.Index(
                fields=["clinic", "date", "status"], name="idx_appts_date_status"
            ),
        ),
        migrations.AddConstraint(
            model_name="appointment",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("status__in", ["scheduled", "confirmed", "in_progress"])
                ),
                fields=("dentist", "date", "start_time"),
                name="uq_dentist_time_slot",
            ),
        ),
        migrations.AddIndex(
            model_name="scheduleslot",
            index=models.Index(
                fields=["clinic", "day_of_week"], name="idx_schedule_day"
            ),
        ),
    ]
