# Generated by Django 5.0.14 on 2026-05-21 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='inventory_consumed_at',
            field=models.DateTimeField(blank=True, help_text='When inventory kit was consumed on completion', null=True),
        ),
    ]
