# Generated by Django 5.0.14 on 2026-05-07 18:01

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("appointments", "0002_initial"),
        ("clinics", "0001_initial"),
        ("patients", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FiscalConfig",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "rfc",
                    models.CharField(
                        db_index=True,
                        help_text="RFC de la clínica (12-13 caracteres)",
                        max_length=13,
                    ),
                ),
                (
                    "razon_social",
                    models.CharField(
                        help_text="Razón social tal como aparece en la Constancia de Situación Fiscal",
                        max_length=255,
                    ),
                ),
                (
                    "regimen_fiscal",
                    models.CharField(
                        help_text="Clave del régimen fiscal SAT (e.g., 601, 606, 612)",
                        max_length=3,
                    ),
                ),
                (
                    "fiscal_address",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Dirección fiscal: {calle, no_exterior, no_interior, colonia, localidad, municipio, estado, pais, codigo_postal}",
                    ),
                ),
                (
                    "csd_cert_path",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Path al archivo .cer del CSD",
                        max_length=500,
                    ),
                ),
                (
                    "csd_key_path",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Path al archivo .key del CSD",
                        max_length=500,
                    ),
                ),
                (
                    "csd_password_encrypted",
                    models.BinaryField(
                        blank=True,
                        help_text="Contraseña del CSD encriptada con AES-256-GCM",
                        null=True,
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        default="",
                        help_text="Email para envío de facturas",
                        max_length=254,
                    ),
                ),
                (
                    "is_validated",
                    models.BooleanField(
                        default=False,
                        help_text="True si el CSD fue validado exitosamente contra el SAT",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "clinic",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fiscal_config",
                        to="clinics.clinic",
                    ),
                ),
            ],
            options={
                "db_table": "fiscal_configs",
                "ordering": ["-created_at"],
                "indexes": [models.Index(fields=["rfc"], name="idx_fiscal_rfc")],
            },
        ),
        migrations.CreateModel(
            name="Invoice",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "folio",
                    models.CharField(
                        db_index=True,
                        help_text="Folio consecutivo de la factura",
                        max_length=20,
                    ),
                ),
                (
                    "rfc_receptor",
                    models.CharField(
                        db_index=True,
                        help_text="RFC del paciente/receptor",
                        max_length=13,
                    ),
                ),
                (
                    "nombre_receptor",
                    models.CharField(
                        help_text="Nombre o razón social del receptor", max_length=255
                    ),
                ),
                (
                    "uso_cfdi",
                    models.CharField(
                        choices=[
                            ("G03", "Gastos en general"),
                            (
                                "D01",
                                "Honorarios médicos, dentales y gastos hospitalarios",
                            ),
                            ("S01", "Sin efectos fiscales"),
                            ("CP01", "Pagos"),
                        ],
                        default="G03",
                        help_text="Uso de CFDI según catálogo SAT",
                        max_length=10,
                    ),
                ),
                (
                    "metodo_pago",
                    models.CharField(
                        choices=[
                            ("PUE", "Pago en una sola exhibición"),
                            ("PPD", "Pago en parcialidades o diferido"),
                        ],
                        default="PUE",
                        max_length=3,
                    ),
                ),
                (
                    "forma_pago",
                    models.CharField(
                        choices=[
                            ("01", "Efectivo"),
                            ("04", "Tarjeta de débito"),
                            ("03", "Transferencia electrónica"),
                            ("06", "Monedero electrónico"),
                            ("99", "Por definir"),
                        ],
                        default="01",
                        max_length=2,
                    ),
                ),
                (
                    "moneda",
                    models.CharField(
                        choices=[
                            ("MXN", "Peso Mexicano"),
                            ("USD", "Dólar Estadounidense"),
                        ],
                        default="MXN",
                        max_length=3,
                    ),
                ),
                (
                    "subtotal",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Suma de los importes antes de impuestos",
                        max_digits=12,
                    ),
                ),
                (
                    "iva",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="IVA (16% typically)",
                        max_digits=12,
                    ),
                ),
                (
                    "total",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="subtotal + iva",
                        max_digits=12,
                    ),
                ),
                (
                    "concepts",
                    models.JSONField(
                        default=list,
                        help_text="Lista de conceptos: [{clave_sat, descripcion, cantidad, unidad, valor_unitario, importe, iva_rate}]",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Borrador"),
                            ("pending_stamp", "Pendiente de timbrado"),
                            ("stamped", "Timbrada"),
                            ("sent", "Enviada al cliente"),
                            ("paid", "Pagada"),
                            ("cancelled", "Cancelada"),
                            ("cancellation_requested", "Cancelación solicitada"),
                            ("error", "Error"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=30,
                    ),
                ),
                (
                    "cfdi_uuid",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        help_text="UUID del CFDI asignado por el SAT",
                        max_length=36,
                    ),
                ),
                (
                    "xml_url",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="URL para descargar el XML timbrado",
                        max_length=500,
                    ),
                ),
                (
                    "pdf_url",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="URL para descargar la representación impresa PDF",
                        max_length=500,
                    ),
                ),
                (
                    "cfdi_sat_certificate",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Número de certificado del SAT usado para timbrar",
                        max_length=40,
                    ),
                ),
                (
                    "cfdi_stamp_date",
                    models.DateTimeField(
                        blank=True, help_text="Fecha de timbrado del CFDI", null=True
                    ),
                ),
                (
                    "cancellation_reason",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Motivo de cancelación SAT: 01, 02, 03, 04",
                        max_length=20,
                    ),
                ),
                (
                    "cancellation_folio",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Folio de sustitución si aplica (motivo 01)",
                        max_length=200,
                    ),
                ),
                ("cancelled_at", models.DateTimeField(blank=True, null=True)),
                (
                    "error_message",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Mensaje de error del último intento de timbrado",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "appointment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="invoices",
                        to="appointments.appointment",
                    ),
                ),
                (
                    "clinic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invoices",
                        to="clinics.clinic",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_invoices",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="invoices",
                        to="patients.patient",
                    ),
                ),
            ],
            options={
                "db_table": "invoices",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["clinic", "status"], name="idx_invoices_clinic_status"
                    ),
                    models.Index(
                        fields=["clinic", "created_at"], name="idx_invoices_created"
                    ),
                    models.Index(
                        fields=["patient", "created_at"], name="idx_invoices_patient"
                    ),
                    models.Index(fields=["cfdi_uuid"], name="idx_invoices_uuid"),
                    models.Index(fields=["folio"], name="idx_invoices_folio"),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="invoice",
            constraint=models.UniqueConstraint(
                fields=("clinic", "folio"), name="uq_invoice_clinic_folio"
            ),
        ),
    ]
