# Generated by Django 5.0.14 on 2026-05-07 18:01

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Clinic",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("rfc", models.CharField(db_index=True, max_length=13, unique=True)),
                ("email", models.EmailField(db_index=True, max_length=254)),
                ("phone", models.CharField(blank=True, max_length=15)),
                ("address", models.JSONField(blank=True, default=dict)),
                (
                    "plan",
                    models.CharField(
                        choices=[("free", "Free"), ("basic", "Basic"), ("pro", "Pro")],
                        default="free",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("active", "Active"),
                            ("suspended", "Suspended"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("email_verified", models.BooleanField(default=False)),
                (
                    "email_verification_token",
                    models.CharField(blank=True, max_length=128, null=True),
                ),
                (
                    "email_verification_expires",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("subscription_start", models.DateField(blank=True, null=True)),
                ("subscription_end", models.DateField(blank=True, null=True)),
                ("onboarding_completed", models.BooleanField(default=False)),
                ("settings", models.JSONField(blank=True, default=dict)),
                ("cfdi_config", models.JSONField(blank=True, default=dict)),
                ("stamps_remaining", models.PositiveIntegerField(default=50)),
                ("is_deleted", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "clinics",
                "indexes": [
                    models.Index(fields=["rfc"], name="idx_clinics_rfc"),
                    models.Index(fields=["status"], name="idx_clinics_status"),
                    models.Index(fields=["plan"], name="idx_clinics_plan"),
                    models.Index(
                        fields=["email_verified"], name="idx_clinics_email_verified"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="OnboardingStep",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "step_name",
                    models.CharField(
                        choices=[
                            ("clinic_info", "Información de la clínica"),
                            ("team_setup", "Configuración del equipo"),
                            ("schedule_config", "Configuración de horarios"),
                            ("patient_import", "Importación de pacientes"),
                            ("fiscal_config", "Configuración fiscal"),
                            ("whatsapp_config", "Configuración de WhatsApp"),
                        ],
                        max_length=50,
                    ),
                ),
                ("completed", models.BooleanField(default=False)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "clinic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="onboarding_steps",
                        to="clinics.clinic",
                    ),
                ),
            ],
            options={
                "db_table": "onboarding_steps",
                "ordering": ["created_at"],
                "unique_together": {("clinic", "step_name")},
            },
        ),
    ]
