# Generated by Django 5.0.14 on 2026-05-07 18:01

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("clinics", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="InventoryItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True, default="")),
                (
                    "sku",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=50
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("material", "Material"),
                            ("supply", "Insumo"),
                            ("instrument", "Instrumento"),
                            ("medication", "Medicamento"),
                            ("lab", "Laboratorio"),
                            ("other", "Otro"),
                        ],
                        db_index=True,
                        default="supply",
                        max_length=20,
                    ),
                ),
                (
                    "unit",
                    models.CharField(
                        default="pieza",
                        help_text="Unit of measure (pieza, caja, ml, gr, etc.)",
                        max_length=20,
                    ),
                ),
                (
                    "stock_current",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Current stock quantity",
                        max_digits=10,
                    ),
                ),
                (
                    "stock_minimum",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Minimum stock level — triggers alert when below",
                        max_digits=10,
                    ),
                ),
                (
                    "stock_maximum",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Maximum stock level (optional reorder cap)",
                        max_digits=10,
                    ),
                ),
                (
                    "expiration_date",
                    models.DateField(blank=True, db_index=True, null=True),
                ),
                (
                    "batch_number",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                ("is_expired", models.BooleanField(db_index=True, default=False)),
                (
                    "is_blocked",
                    models.BooleanField(
                        default=False,
                        help_text="Blocked items cannot be used or consumed",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "unit_price",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Unit cost from supplier",
                        max_digits=10,
                    ),
                ),
                (
                    "cost",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "price",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("supplier", models.CharField(blank=True, default="", max_length=200)),
                (
                    "supplier_sku",
                    models.CharField(blank=True, default="", max_length=50),
                ),
                (
                    "barcode",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=100
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "clinic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inventory_items",
                        to="clinics.clinic",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_inventory_items",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "inventory_items",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="InventoryMovement",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "movement_type",
                    models.CharField(
                        choices=[
                            ("in", "Entrada"),
                            ("out", "Salida"),
                            ("adjustment", "Ajuste"),
                            ("consumption", "Consumo automático"),
                            ("return", "Devolución"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Signed quantity: positive for in, negative for out",
                        max_digits=10,
                    ),
                ),
                (
                    "previous_stock",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Stock before this movement",
                        max_digits=10,
                    ),
                ),
                (
                    "new_stock",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Stock after this movement",
                        max_digits=10,
                    ),
                ),
                (
                    "reference_type",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Type of reference (appointment, manual, purchase_order)",
                        max_length=50,
                    ),
                ),
                (
                    "reference_id",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="ID of the reference object",
                        max_length=100,
                    ),
                ),
                ("note", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "clinic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inventory_movements",
                        to="clinics.clinic",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_inventory_movements",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="movements",
                        to="inventory.inventoryitem",
                    ),
                ),
            ],
            options={
                "db_table": "inventory_movements",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="inventoryitem",
            index=models.Index(fields=["clinic", "category"], name="idx_inv_category"),
        ),
        migrations.AddIndex(
            model_name="inventoryitem",
            index=models.Index(fields=["clinic", "is_active"], name="idx_inv_active"),
        ),
        migrations.AddIndex(
            model_name="inventoryitem",
            index=models.Index(
                fields=["clinic", "stock_current", "stock_minimum"],
                name="idx_inv_stock_levels",
            ),
        ),
        migrations.AddIndex(
            model_name="inventoryitem",
            index=models.Index(fields=["clinic", "is_expired"], name="idx_inv_expired"),
        ),
        migrations.AddIndex(
            model_name="inventoryitem",
            index=models.Index(
                fields=["clinic", "expiration_date"], name="idx_inv_expiration"
            ),
        ),
        migrations.AddConstraint(
            model_name="inventoryitem",
            constraint=models.CheckConstraint(
                check=models.Q(("stock_current__gte", 0)),
                name="chk_stock_current_non_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="inventoryitem",
            constraint=models.CheckConstraint(
                check=models.Q(("stock_minimum__gte", 0)),
                name="chk_stock_minimum_non_negative",
            ),
        ),
        migrations.AddIndex(
            model_name="inventorymovement",
            index=models.Index(fields=["clinic", "item"], name="idx_mov_item"),
        ),
        migrations.AddIndex(
            model_name="inventorymovement",
            index=models.Index(fields=["clinic", "movement_type"], name="idx_mov_type"),
        ),
        migrations.AddIndex(
            model_name="inventorymovement",
            index=models.Index(
                fields=["clinic", "reference_type", "reference_id"],
                name="idx_mov_reference",
            ),
        ),
        migrations.AddIndex(
            model_name="inventorymovement",
            index=models.Index(fields=["clinic", "created_at"], name="idx_mov_created"),
        ),
    ]
