"""
CFDI 4.0 XML builder service.

Builds a valid CFDI 4.0 XML document from an Invoice model instance,
signs it with the clinic's CSD (Certificado de Sello Digital), and
encodes it as base64 for submission to Finkok.

CFDI 4.0 structure:
- <cfdi:Comprobante> — root element with invoice totals and metadata
  - <cfdi:Emisor> — issuer (clinic) fiscal data
  - <cfdi:Receptor> — receiver (patient) fiscal data
  - <cfdi:Conceptos> — line items
    - <cfdi:Concepto> — individual line item
      - <cfdi:Impuestos> — taxes per concept
        - <cfdi:Traslado> — IVA traslado
  - <cfdi:Impuestos> — global taxes summary
    - <cfdi:Traslados> — IVA total

Sello (seal) is generated by:
1. Creating the original string (cadena original) using XSLT
2. SHA-256 hashing the cadena original
3. Signing the hash with the CSD private key
4. Encoding the signature as base64
"""

import base64
import hashlib
import logging
from datetime import datetime, timezone
from decimal import Decimal
from typing import Any
from xml.etree import ElementTree as ET

from cryptography.hazmat.primitives import hashes, serialization
from cryptography.hazmat.primitives.asymmetric import padding

logger = logging.getLogger(__name__)

# CFDI namespaces
NS_CFDI = "http://www.sat.gob.mx/cfd/4"
NS_XSI = "http://www.w3.org/2001/XMLSchema-instance"
NS_MAP = {
    "cfdi": NS_CFDI,
    "xsi": NS_XSI,
}

# SAT catalog codes
MONEDA_MXN = "MXN"
EXPEDITION_PLACE_DEFAULT = "06300"  # Default CP (override with fiscal_address)


def build_cfdi_xml(invoice: Any, fiscal_config: Any) -> str:
    """
    Build a CFDI 4.0 XML document from an Invoice and FiscalConfig.

    Args:
        invoice: Invoice model instance.
        fiscal_config: FiscalConfig model instance.

    Returns:
        Complete CFDI XML as string (without sello/certificado — PAC adds those).
    """
    # Build the Comprobante element
    comprobante = _build_comprobante(invoice, fiscal_config)

    # Add Emisor
    _add_emisor(comprobante, fiscal_config)

    # Add Receptor
    _add_receptor(comprobante, invoice)

    # Add Conceptos
    _add_conceptos(comprobante, invoice)

    # Add Impuestos (global taxes)
    _add_impuestos(comprobante, invoice)

    # Register namespaces to avoid ns0, ns1 prefixes
    for prefix, uri in NS_MAP.items():
        ET.register_namespace(prefix, uri)

    # Generate XML string
    xml_string = ET.tostring(comprobante, encoding="unicode", xml_declaration=False)

    # Add XML declaration
    xml_with_decl = '<?xml version="1.0" encoding="UTF-8"?>\n' + xml_string

    return xml_with_decl


def sign_cfdi(
    xml_string: str,
    cert_path: str,
    key_path: str,
    key_password: bytes,
) -> str:
    """
    Sign a CFDI XML with the CSD certificate and private key.

    Adds:
    - certificado attribute (base64 of the .cer file)
    - sello attribute (base64 of the RSA-SHA256 signature)
    - noCertificado attribute

    Args:
        xml_string: The CFDI XML string.
        cert_path: Path to the .cer file.
        key_path: Path to the .key file.
        key_password: Decrypted CSD password.

    Returns:
        Signed CFDI XML string.
    """
    # Load certificate
    with open(cert_path, "rb") as f:
        cert_data = f.read()

    cert_b64 = base64.b64encode(cert_data).decode("ascii")

    # Extract certificate serial number
    from cryptography import x509

    cert = x509.load_der_x509_certificate(cert_data)
    cert_serial = _format_cert_serial(cert.serial_number)

    # Load private key
    with open(key_path, "rb") as f:
        key_data = f.read()

    private_key = serialization.load_der_private_key(
        key_data,
        password=key_password,
    )

    # Build cadena original (simplified — in production, use SAT XSLT)
    cadena_original = _build_cadena_original(xml_string, cert_serial)

    # Sign the cadena original
    signature = private_key.sign(
        cadena_original.encode("utf-8"),
        padding.PKCS1v15(),
        hashes.SHA256(),
    )
    sello = base64.b64encode(signature).decode("ascii")

    # Inject certificado and sello into the Comprobante element
    xml_string = xml_string.replace(
        "<cfdi:Comprobante ",
        f'<cfdi:Comprobante certificado="{cert_b64}" sello="{sello}" noCertificado="{cert_serial}" ',
    )

    return xml_string


def encode_for_finkok(xml_string: str) -> str:
    """
    Encode a CFDI XML as base64 for Finkok submission.

    Args:
        xml_string: The CFDI XML string.

    Returns:
        Base64-encoded string.
    """
    return base64.b64encode(xml_string.encode("utf-8")).decode("ascii")


# ---------------------------------------------------------------------------
# Internal helpers
# ---------------------------------------------------------------------------


def _build_comprobante(invoice: Any, fiscal_config: Any) -> ET.Element:
    """Build the root Comprobante element."""
    attrs = {
        "xmlns:cfdi": NS_CFDI,
        "xmlns:xsi": NS_XSI,
        "Version": "4.0",
        "Serie": "A",
        "Folio": invoice.folio,
        "Fecha": datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%S"),
        "FormaPago": invoice.forma_pago,
        "NoCertificado": "",  # Filled by sign_cfdi
        "CondicionesDePago": "",
        "SubTotal": _fmt_decimal(invoice.subtotal),
        "Descuento": "0.00",
        "Moneda": invoice.moneda,
        "TipoCambio": "1",
        "Total": _fmt_decimal(invoice.total),
        "TipoDeComprobante": "I",  # Ingreso
        "Exportacion": "01",  # No aplica
        "MetodoPago": invoice.metodo_pago,
        "LugarExpedicion": _get_expedition_place(fiscal_config),
        "Confirmacion": "",
        "xsi:schemaLocation": f"{NS_CFDI} http://www.sat.gob.mx/sitio_internet/cfd/4/cfdv40.xsd",
    }

    return ET.Element("cfdi:Comprobante", attrs)


def _add_emisor(parent: ET.Element, fiscal_config: Any) -> None:
    """Add Emisor (issuer) element."""
    attrs = {
        "Rfc": fiscal_config.rfc,
        "Nombre": fiscal_config.razon_social,
        "RegimenFiscal": fiscal_config.regimen_fiscal,
    }
    ET.SubElement(parent, "cfdi:Emisor", attrs)


def _add_receptor(parent: ET.Element, invoice: Any) -> None:
    """Add Receptor (receiver) element."""
    attrs = {
        "Rfc": invoice.rfc_receptor,
        "Nombre": invoice.nombre_receptor,
        "DomicilioFiscalReceptor": _get_receptor_cp(invoice),
        "ResidenciaFiscal": "",
        "NumRegIdTrib": "",
        "RegimenFiscalReceptor": _get_receptor_regimen(invoice.rfc_receptor),
        "UsoCFDI": invoice.uso_cfdi,
    }
    ET.SubElement(parent, "cfdi:Receptor", attrs)


def _add_conceptos(parent: ET.Element, invoice: Any) -> None:
    """Add Conceptos (line items) element."""
    conceptos = ET.SubElement(parent, "cfdi:Conceptos")

    for concept in invoice.concepts:
        attrs = {
            "ClaveProdServ": concept.get("clave_sat", "84111506"),
            "NoIdentificacion": "",
            "Cantidad": _fmt_decimal(concept.get("cantidad", 1)),
            "ClaveUnidad": concept.get("unidad", "ACT"),
            "Unidad": "",
            "Descripcion": concept.get("descripcion", ""),
            "ValorUnitario": _fmt_decimal(concept.get("valor_unitario", 0)),
            "Importe": _fmt_decimal(concept.get("importe", 0)),
            "Descuento": "0.00",
            "ObjetoImp": "02",  # Sí objeto de impuesto
        }
        concepto = ET.SubElement(conceptos, "cfdi:Concepto", attrs)

        # Add IVA traslado if applicable
        iva_rate = concept.get("iva_rate", 0.16)
        if iva_rate > 0:
            impuestos = ET.SubElement(concepto, "cfdi:Impuestos")
            traslados = ET.SubElement(impuestos, "cfdi:Traslados")
            ET.SubElement(
                traslados,
                "cfdi:Traslado",
                {
                    "Base": _fmt_decimal(concept.get("importe", 0)),
                    "Impuesto": "002",  # IVA
                    "TipoFactor": "Tasa",
                    "TasaOCuota": _fmt_decimal(iva_rate),
                    "Importe": _fmt_decimal(concept.get("importe", 0) * iva_rate),
                },
            )


def _add_impuestos(parent: ET.Element, invoice: Any) -> None:
    """Add global Impuestos element."""
    impuestos = ET.SubElement(parent, "cfdi:Impuestos")

    # Calculate total IVA
    total_iva = Decimal(str(invoice.iva))

    if total_iva > 0:
        traslados = ET.SubElement(impuestos, "cfdi:Traslados")
        ET.SubElement(
            traslados,
            "cfdi:Traslado",
            {
                "Impuesto": "002",  # IVA
                "TipoFactor": "Tasa",
                "TasaOCuota": "0.160000",
                "Importe": _fmt_decimal(total_iva),
            },
        )

    impuestos.set("TotalImpuestosTrasladados", _fmt_decimal(total_iva))


def _build_cadena_original(xml_string: str, cert_serial: str) -> str:
    """
    Build the cadena original for signing.

    In production, this should use the SAT-provided XSLT transformation.
    This is a simplified version for the MVP.

    The cadena original format for CFDI 4.0:
    ||4.0|Serie|Folio|Fecha|...||
    """
    # Parse XML to extract attributes
    root = ET.fromstring(xml_string)

    parts = [
        "||4.0",
        root.get("Serie", ""),
        root.get("Folio", ""),
        root.get("Fecha", ""),
        root.get("FormaPago", ""),
        root.get("SubTotal", ""),
        root.get("Descuento", ""),
        root.get("Moneda", ""),
        root.get("Total", ""),
        root.get("TipoDeComprobante", ""),
        root.get("MetodoPago", ""),
        root.get("LugarExpedicion", ""),
    ]

    # Emisor
    emisor = root.find("cfdi:Emisor", NS_MAP)
    if emisor is not None:
        parts.extend(
            [
                emisor.get("Rfc", ""),
                emisor.get("Nombre", ""),
                emisor.get("RegimenFiscal", ""),
            ]
        )

    # Receptor
    receptor = root.find("cfdi:Receptor", NS_MAP)
    if receptor is not None:
        parts.extend(
            [
                receptor.get("Rfc", ""),
                receptor.get("Nombre", ""),
                receptor.get("UsoCFDI", ""),
            ]
        )

    # Conceptos
    conceptos = root.find("cfdi:Conceptos", NS_MAP)
    if conceptos is not None:
        for concepto in conceptos.findall("cfdi:Concepto", NS_MAP):
            parts.extend(
                [
                    concepto.get("ClaveProdServ", ""),
                    concepto.get("Cantidad", ""),
                    concepto.get("ClaveUnidad", ""),
                    concepto.get("Descripcion", ""),
                    concepto.get("ValorUnitario", ""),
                    concepto.get("Importe", ""),
                ]
            )

    # Impuestos
    impuestos = root.find("cfdi:Impuestos", NS_MAP)
    if impuestos is not None:
        total_trasladados = impuestos.get("TotalImpuestosTrasladados", "0.00")
        parts.append(total_trasladados)

        traslados = impuestos.find("cfdi:Traslados", NS_MAP)
        if traslados is not None:
            for traslado in traslados.findall("cfdi:Traslado", NS_MAP):
                parts.extend(
                    [
                        traslado.get("Impuesto", ""),
                        traslado.get("TipoFactor", ""),
                        traslado.get("TasaOCuota", ""),
                        traslado.get("Importe", ""),
                    ]
                )

    return "|".join(parts) + "||"


def _format_cert_serial(serial_number: int) -> str:
    """Format certificate serial number as 20-digit hex string."""
    return f"{serial_number:020X}"


def _fmt_decimal(value: Any) -> str:
    """Format a decimal value with 2 decimal places."""
    return f"{Decimal(str(value)):.2f}"


def _get_expedition_place(fiscal_config: Any) -> str:
    """Get the expedition place (CP) from fiscal address."""
    address = fiscal_config.fiscal_address or {}
    return address.get("codigo_postal", EXPEDITION_PLACE_DEFAULT)


def _get_receptor_cp(invoice: Any) -> str:
    """Get receptor's fiscal CP (default to generic if unknown)."""
    # In production, look up from patient address
    # For MVP, use a generic value
    return "06300"


def _get_receptor_regimen(rfc: str) -> str:
    """Determine receptor's fiscal regime based on RFC format."""
    # Person moral (12 chars) vs person fisica (13 chars)
    if len(rfc) == 12:
        return "601"  # General de Ley Personas Morales
    return "605"  # Sueldos y Salarios (persona física)
