# Generated by Django 5.0.14 on 2026-05-20 18:27

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clinics', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(db_index=True, max_length=100)),
                ('resource_type', models.CharField(db_index=True, max_length=50)),
                ('resource_id', models.UUIDField(db_index=True)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('result', models.CharField(choices=[('success', 'Success'), ('failure', 'Failure')], default='success', max_length=20)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('request_id', models.CharField(blank=True, db_index=True, max_length=36)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='clinics.clinic')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'audit_logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['clinic', 'created_at'], name='idx_audit_clinic_date'), models.Index(fields=['clinic', 'resource_type'], name='idx_audit_clinic_type'), models.Index(fields=['user', 'created_at'], name='idx_audit_user_date'), models.Index(fields=['action'], name='idx_audit_action')],
            },
        ),
    ]
